// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gowdzpmgukttnvzxilmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdvd2R6cG1ndWt0dG52enhpbG13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMjY3OTUsImV4cCI6MjA3MDcwMjc5NX0.hd9HNaXIzKQUOgfqks2CmbFMbj1X1KQGgG9kNrCFRaI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});